all:
  hosts:
    oken-cars:
      ansible_host: 10.10.10.31
      domain_name: oken-cars.oken.lan
    oken-cars2:
      ansible_host: 10.10.10.32
      domain_name: oken-cars2.oken.lan
    oken-cars3:
      ansible_host: 10.10.10.33
      domain_name: oken-cars3.oken.lan

  vars:
    ansible_user: oken
    ansible_ssh_private_key_file: ./.ssh/id_rsa

  children:
    ssh_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:

    java_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:

    maven_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:

    nodejs_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:

    docker_compose_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:

    ufw_hosts:
      hosts:
        oken-cars:
        oken-cars2:
        oken-cars3:
