TRUNCATE TABLE DRIVER RESTART IDENTITY;
TRUNCATE TABLE managers RESTART IDENTITY;

TRUNCATE TABLE cars RESTART IDENTITY;
TRUNCATE TABLE owners RESTART IDENTITY;
TRUNCATE TABLE CUSTOMER RESTART IDENTITY;
TRUNCATE TABLE LOCATION RESTART IDENTITY;

