---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true
